build:
  - source: ./images/git/image.yaml
    destination: ghcr.io/platformfuzz/images/git:latest
  - source: ./images/mkdocs_material/Dockerfile
    destination: ghcr.io/platformfuzz/images/mkdocs_material:latest
