sync:
  # NOTES
  # - use an image with digest for the source (use `crane digest IMAGE_REF` to find it); ensuring the exact image is used and the tag can't be swapped underneath
  # NOTE use the following command to check if each image resolves
  #      yq e .sync[].source ./config.yaml | xargs -n 1 -I{} sh -c 'printf "{} => "; crane digest {}'
  - source: docker.io/library/alpine:3.18@sha256:02bb6f428431fbc2809c5d1b41eab5a68350194fb508869a33cb1af4444c9b11
    destination: ghcr.io/geonet/base-images/alpine:3.18 # latest alpine
  - source: docker.io/redhat/ubi8:8.8@sha256:a7143118671dfc61aca46e8ab9e488500495a3c4c73a69577ca9386564614c13
    destination: ghcr.io/geonet/base-images/ubi8:8.8
  - source: docker.io/redhat/ubi8-minimal:8.8@sha256:621f5245fb3e8597a626163cdf1229e1f8311e07ab71bb1e9332014b51c59f9c
    destination: ghcr.io/geonet/base-images/ubi8-minimal:8.8
  - source: docker.io/datadog/agent:7@sha256:b9e11fd44fec2dc6f42d7d8eeafb29dc16bc185af37c395b9c3864b1402134d0
    destination: ghcr.io/geonet/base-images/datadog/agent:7
  - source: docker.io/library/debian:bookworm-slim@sha256:d8f9d38c21495b04d1cca99805fbb383856e19794265684019bf193c3b7d67f9
    destination: ghcr.io/geonet/base-images/debian:bookworm-slim
  - source: docker.io/hadolint/hadolint:v2.12.0-alpine@sha256:3c206a451cec6d486367e758645269fd7d696c5ccb6ff59d8b03b0e45268a199
    destination: ghcr.io/geonet/base-images/hadolint/hadolint:v2.12.0-alpine
  - source: docker.io/hashicorp/terraform:1.5.0@sha256:9771ed388877ad208d596b895918b0ea068587e3f72a01ec0215cf972619df75
    destination: ghcr.io/geonet/base-images/hashicorp/terraform:1.5.0
  - source: docker.io/library/node:16.17.1-alpine@sha256:4d68856f48be7c73cd83ba8af3b6bae98f4679e14d1ff49e164625ae8831533a # older node
    destination: ghcr.io/geonet/base-images/node:16.17.1-alpine
  - source: docker.io/library/node:20.3-alpine3.18@sha256:30d5045fa5026abaed7439b62d51f73ac3efd1009496271d4c85fd83bb20144e # latest node
    destination: ghcr.io/geonet/base-images/node:20.3-alpine3.18
  - source: docker.io/library/python:3.11.4-bullseye@sha256:e76a365d3f3b37ad4cf4bae474a063883461b01e07e2f51cd7d9597fd455ee38
    destination: ghcr.io/geonet/base-images/python:3.11.4-bullseye
  - source: docker.io/library/python:3.11.4-alpine3.18@sha256:995c7fcdf9a10e0e1a4555861dac63436b456822a167f07b6599d4f105de6fa0
    destination: ghcr.io/geonet/base-images/python:3.11.4-alpine3.18
  - source: docker.io/library/golang:1.16-alpine3.15@sha256:5616dca835fa90ef13a843824ba58394dad356b7d56198fb7c93cbe76d7d67fe
    destination: ghcr.io/geonet/base-images/go:1.16 # until ko has been fully adopted and Go 1.16 => 1.20/1.21
  - source: docker.io/golang:1.20.8-alpine3.18@sha256:c63dbdb3cca37abbee4c50f61e34b1d043c2669d03f34485f9ee6fe5feed4e48
    destination: ghcr.io/geonet/base-images/go:1.20 # until ko has been fully adopted
  - source: docker.io/golang:1.21.1-alpine3.18@sha256:96634e55b363cb93d39f78fb18aa64abc7f96d372c176660d7b8b6118939d97b
    destination: ghcr.io/geonet/base-images/go:1.21 # until ko has been fully adopted
  - source: cgr.dev/chainguard/static:latest@sha256:da9822ad6f973e40e24e75133b08ae874900766873ecd03e58f7f630ccea898c
    destination: ghcr.io/geonet/base-images/static:latest
  - source: cgr.dev/chainguard/nginx:latest@sha256:8c05680b8a70b49013f9011cba5b50b26683e3360280a6065d30ef0cd8a50524 # use for Go base images
    destination: ghcr.io/geonet/base-images/nginx:latest
  - source: cgr.dev/chainguard/node:20@sha256:38dc35af8d4bd8f59c1d8b88999e7dee9746dcee0f375848fb9701f3b61564e5 # latest node
    destination: ghcr.io/geonet/base-images/node:20
  - source: ghcr.io/geonet/base-images/mkdocs_plus:latest@sha256:d54c497b4ec5cce0c41b84e6afe5e4250c0b6ba499832ee977137f0f5e9c8a77
    destination: ghcr.io/geonet/base-images/mkdocs_plus:2023-06-14
  - source: ghcr.io/siderolabs/conform:v0.1.0-alpha.27@sha256:60e5c3cac83104077aff44a86518972f92cffb48d06c06486fb1f2711d4eb559
    destination: ghcr.io/geonet/base-images/siderolabs-conform:v0.1.0-alpha.27
  - source: quay.io/fedora/fedora@sha256:1972716109b1c906120061063bd4cb50a46c2138d95002ccb90126928d98e013
    destination: ghcr.io/geonet/base-images/fedora:38
  - source: quay.io/fedora/fedora-coreos:stable@sha256:022deff7c7249e75604396e507ba823d61dd3b7e94ad7fb3d8682c0cee1619ae # stable for 2023-09-21
    destination: ghcr.io/geonet/base-images/fedora-coreos:stable
    auto-update-mutable-tag-digest: true
  - source: quay.io/centos/centos:7@sha256:e4ca2ed0202e76be184e75fb26d14bf974193579039d5573fb2348664deef76e # 7 for 2023-09-21
    destination: ghcr.io/geonet/base-images/centos:centos7
    auto-update-mutable-tag-digest: true
  - source: quay.io/centos/centos:stream8@sha256:039dfede2e3ab9093411ac1054697eeefa6272ab57092f6c804b53cf937b8bb2 # stream8 for 2023-09-21
    destination: ghcr.io/geonet/base-images/centos:stream8
    auto-update-mutable-tag-digest: true
  - source: quay.io/centos/centos:stream9@sha256:8479941327a5852c72f17305543f676eb797e8080e470b2f164ad8b581917aa6 # stream9 for 2023-09-21
    destination: ghcr.io/geonet/base-images/centos:stream9
    auto-update-mutable-tag-digest: true
  - source: cgr.dev/chainguard/curl:8.1.2@sha256:73992422b3e634c520483bb0aeda22c405d4701ccf5c2294c71d7f67373301cb
    destination: ghcr.io/geonet/base-images/curl:8.1.2
  - source: docker.io/owasp/zap2docker-stable:2.11.1@sha256:47ba18f36de06f253e655d26ad78945c6dc24404e58f1c0758293a583bb99ce5
    destination: ghcr.io/geonet/base-images/owasp/zap2docker-stable:2.11.1
  - source: docker.io/koalaman/shellcheck-alpine:v0.9.0@sha256:e19ed93c22423970d56568e171b4512c9244fc75dd9114045016b4a0073ac4b7
    destination: ghcr.io/geonet/base-images/shellcheck:v0.9.0
build:
  # NOTES
  # - uses dirname of source as context for build
  # - image.yaml for apko based build
  # - Dockerfile for Docker based build
  # - structure like ./images/IMAGE_NAME/...
  # - images are pushed to ghcr.io/geonet/base-images/IMAGE_NAME
  - source: ./images/mkdocs_plus/Dockerfile
    destination: ghcr.io/geonet/base-images/mkdocs_plus:latest
  - source: ./images/git/image.yaml
    destination: ghcr.io/geonet/base-images/git:latest
  - source: ./images/git-ssh/image.yaml
    destination: ghcr.io/geonet/base-images/git-ssh:latest
  - source: ./images/alpine-iputils/image.yaml
    destination: ghcr.io/geonet/base-images/alpine-iputils:3.18
  - source: ./images/alpine-xslt/image.yaml
    destination: ghcr.io/geonet/base-images/alpine-xslt:3.18
  - source: ./images/alpine-gdal/image.yaml
    destination: ghcr.io/geonet/base-images/alpine-gdal:3.18
  - source: ./images/texlive/image.yaml
    destination: ghcr.io/geonet/base-images/texlive:latest
  - source: ./images/chart-centos7/Dockerfile
    destination: ghcr.io/geonet/base-images/chart-centos7:latest
