name: images are public
on:
  push:
    branches:
      - main
jobs:
  images-are-public:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: stable
      - uses: imjasonh/setup-crane@feee3b6bb0d4c68370f256a4502498c9227e5c6b # v0.7
      - name: check images are public
        run: |
          # NOTE: important to not use auth
          jq -r -c '.sync as $sync | .build as $build | {"include":[{"destination": $sync[].destination}, {"destination": $build[].destination}]} | .include[].destination' <<< "$(yq e . -o json config.yaml)" | xargs -n 1 -I{} crane digest {}
